### ISSUE TITLE
The release 1.35.1 was not generated.

### ISSUE THREAD

**Issue by jlpedrosa** [terraform-routeros/terraform-provider-routeros#368]
**Which pipeline fails?:**
The release 1.35.1 was not generated. The pipeline for release did not run.
I have the hunch that probably [here](https://github.com/terraform-routeros/terraform-provider-routeros/blob/main/.github/workflows/release.yml#L23)  the comparision should be `==` instead of `!=` ? 

I also see that for the non release commits, the pipeline ran anyway.

**What job does the pipeline fail on?:**
Pipeline skipped.

![image](https://github.com/terraform-routeros/terraform-provider-routeros/assets/4932947/fe1cf305-4740-417c-a349-3043988134b2)

**Comment by vaerh** [comment]
Yes, there is such a problem. I'll post the artifacts manually soon and see where the build is stuck.

**Comment by vaerh** [comment]
To my regret I can't manually add artifacts, as I don't have some of the necessary parameters for that. 

The release problem is old and is related to overflow in x32 architectures. The idea to fix it is beautiful: `validation.IntBetween(0, math.MaxInt32)`, but it seems to me that we need to remove this validator. It will not work properly in either x32 or x64 architecture (`MaxInt32  = 1<<31 - 1           // 2147483647`). I see two options (to comply with the MT specification):
* remove the validator
* remove the validator and make the parameter a string (to make it work correctly in x32).
I am leaning towards the first option. It is not clear how many people use the provider and this resource on the architecture x32, but the rest I do not see the point of complicating life.

**Comment by jlpedrosa** [comment]
Humm... that is strange. MaxInt32 specify the bit length, so it should work on both. I agree, I don't think that validator is really important. We can also add a very large (int the context of MTU) and call it a day. What ever you think is best.

BTW, is there any way to have a sync conversation @vaerh ?

**Comment by jlpedrosa** [comment]
https://github.com/terraform-routeros/terraform-provider-routeros/pull/380

**Comment by jlpedrosa** [comment]
@vaerh  I saw you added more tags, but still there are no new releases on the terraform page. the build is skipped.

are you sure this code block is correct?
```
jobs:

  release:
    if: contains(github.event.head_commit.message, 'chore(release)') != true
 ```
 
 It feels like the when the commit message contains 'chore(release)' the release pipeline should be executed no?

**Comment by vaerh** [comment]
@jlpedrosa 
Everything is working as expected. The artifacts are in place and should therefore be available in the HashiCorp registry.
[chore(release)](https://github.com/terraform-routeros/terraform-provider-routeros/commit/f0569a585a8cc5f3fcee09e64dc00b3bd1f81170) generates the description and changes the metainformation. Since actions are triggered on every commit to the main branch, this check serves to avoid trying to process commits initialized from actions (there will be a continuous loop).

If we look at the fixations again, the workflow is as follows:
* Commit to the main branch
* Running actions
* Analyzing semantic-release commit names
* Making a release or terminating an action
* Commit data generated by semantic-release

For this reason, the last commit (e.g. `chore(release): 1.37.1`) does not refer to a release.

**Comment by jlpedrosa** [comment]
Hummmm, the provider is still not visible on hasicorp.. https://registry.terraform.io/providers/terraform-routeros/routeros/latest (1.34)

also I can't pull the version:
```
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider terraform-routeros/routeros: no available releases match the given constraints ~> 1.37.1
╵
```

It is just a mater of delay or am I pulling a version that should not be there yet?

**Comment by vaerh** [comment]
Big problem. Thanks. I'll look into it.

**Comment by vaerh** [comment]
I hope it's resolved. Will know for sure after the next release.
