### ISSUE TITLE
reboot router and wait

### ISSUE THREAD

**Issue by Schwitzd** [terraform-routeros/terraform-provider-routeros#526]
**Is your feature request related to a problem? Please describe.**
To apply apply contain resources is needed to manually reboot the router, for example to load the container package.

I have the following code to upload the container package:
```hcl
resource "null_resource" "upload_container_npk" {
  provisioner "local-exec" {
    command = "scp \"/tmp/routeros_packages/${local.container_npk_name}\" ${data.vault_generic_secret.mikrotik.data["user"]}@${var.router_ip}:/${local.container_npk_name}"
  }

  depends_on = [ null_resource.download_container_npk ]
}
```

But then I need to manually reboot. I'm looking for a way to reboot the router, wait the reboot time and continue to provision other resources.

**Describe the solution you'd like**
M/A

**Documentation**
Seems there is an endpoint /system/reboot

**Additional context**
N/A

**Comment by vaerh** [comment]
Unfortunately what you describe is the task of the provisioner, not the resource. The resource has a clear state that TF is trying to bring the controlled object to, and the reboot process is not a control object, it is an effect on the object.

But, unless something has changed since I was wondering about this, TF does not support custom provisioners. Not all endpoints can be realized in the provider unfortunately.

**Comment by Schwitzd** [comment]
[here](https://github.com/Schwitzd/IaC-HomeRouter/blob/main/container_backend.tf) how I solved.
